name: DDPM-cpu
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.12
- pytorch=2.3.1
- torchvision
- pip
- numpy
- matplotlib
- scikit-learn
- scipy
- pandas
- pip:
  - requests
  - torchmetrics
  - tqdm
  - PyYAML