name: DDPM-gpu
channels:
- conda-forge
- defaults
dependencies:
- gxx_linux-64
- python=3.11
- pip
- numpy
- matplotlib
- scikit-learn
- scipy
- pandas
- pip:
  - future
  - tb-nightly
  - pillow
  - ipywidgets
  - einops
  - transformers
  - datasets
  - --extra-index-url https://download.pytorch.org/whl/cu118
  - torch==2.3.1+cu118
  - torchvision==0.18.1+cu118