name: dl-module3-cpu
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.12
- pytorch=2.3.1
- torchvision
- pip
- numpy
- matplotlib
- scikit-learn
- scipy
- pandas
- pip:
  - datasets
  - tensorflow>=2.16
  - tensorflow-datasets
  - requests
  - torchmetrics
  - torch-fidelity
  - tqdm
  - PyYAML
  - huggingface_hub
